### PR TITLE
Delete .travis.yml

### PR DESCRIPTION
**Pull request by caffreyj**
remove travis processing which fails invoking sonarqube

### CODE REVIEW

**Comment by jmertic** [comment]
@caffreyj Please close this PR and re-open it to re-run the checks.

**Comment by caffreyj** [comment]
re running checks

**Comment by caffreyj** [comment]
hopefully fixed CLA

**Comment by caffreyj** [comment]
@jmertic It looks like my id @caffreyj  does not have write access to the repro so I can do a merge.

**Comment by jmertic** [comment]
@caffreyj You need to accept the invitation to this team...

https://github.com/orgs/openmainframeproject/teams/ade-maintainers/

**Comment by caffreyj** [comment]
@jmertic I got a 404 for that link because the invitation looks like it has expired

**Comment by jmertic** [comment]
Resent invite - let me know if that works.

**Comment by caffreyj** [comment]
@jmertic success

**Pull request merged**
