### PR TITLE
Add support for Spark logs

### PR DESCRIPTION
**Pull request by ayush-1506**
This PR summarizes my work as an OMP intern. The aim of the project is to expand support to spark logs in ade. The changes in this PR also include additional spark log data to train and analyze the model (in `ade-assembly/src/main/baseline/spark/`). Other changes include:

New files:

1.  TestSparklogParserBase.java
2.  TestSparklogLineParser.java
3.  SparklogParserBase.java
4.  SparklogParser.java
5.  SparklogMessageReader.java
6.  SparklogLineParser.java
7.  SparkAnalysisGroupToFlowNameConstantMapper.java
8. spark_analysis_comp_test.sh
9. FlowLayoutSpark.xml
10. FlowLayoutSpark.xsd
11. upload/spark.tar.gz
12. analyze/spark_analyze.tar.gz

Edited files:
1.  AdeExtConfigProperties.java
2.  ReaderFactory.java
3.  AdeInputStreamHandlerLinux.java
4.  AdeMaskLog.java
5.  FlowFactory.java
6. .gitignore
7.  AdeConfigPropertiesImpl.java
8.  IAdeConfigProperties.java
9. setup.props

Training and analyzing:

Spin up a derby server `./<path_to_derby>/bin/startNetworkServer`. (Project assumes db-derby 10.11.1.1 is installed). Run the spark_analysis_comp_test.sh (`./bin/test/spark_analysis_comp_test.sh`) file. This should train the model on the data defined in spark.tar.gz and generate analysis files for the data in spark_analyze.tar.gz. Internally, this creates a temporary database, uploads all training files, creates and trains the model groups and performs the analysis. Warning: This might take a while. If you need more data, feel free to contact me. (Training on ~500 mb of data can take more than 2 days, considering the density of these logs.)

### CODE REVIEW

**Comment by ayush-1506** [comment]
@caffreyj Looks like the CI has to be updated (along with the CLA agreements).

**Review by caffreyjm — COMMENTED** [review]
For all new parts please change copy rights from 
`Copyright IBM Corp. 2010, 2016`  to `Copyright Linux Foundation - OpenMainFrame Project 2020`


For all existing parts which were updated after `Copyright IBM Corp. 2010, 2016`  please add the following line  `Copyright Linux Foundation - OpenMainFrame Project 2020`

We might have to change the Linux Foundation copyright after I talk with John Metric

**Comment by ayush-1506** [comment]
@caffreyjm Updated the copy right, removed .travis.yml and fixed DCO.

**Comment by jmertic** [comment]
@ayush-1506  Please close this PR and re-open it to re-run the checks.

**Comment by ayush-1506** [comment]
@jmertic Thanks; all tests pass now.

**Comment by ayush-1506** [comment]
@caffreyjm Can you merge all the changes into master?

**Pull request merged**
