### PR TITLE
Add MariaDB support to ADE.

### PR DESCRIPTION
**Pull request by nealef**
There are several changes required to support MariaDB:

1. Unlike the rest of the namespace where mysql is synonymous with MariaDB the driver name for MariaDB is different
2. An additional statement needs changing at run time to support the MariaDB syntax
3. An unlock is still required at end transaction time regardless of autocommit setting
4. MariaDB has different locking requirements so much of the work is related to implementing this. If you lock a table and then try and access another table which is not locked MariaDB will complain:

```
2016-03-01 05:20:13,971 [main] INFO  (ExtControlProgram.java:138) - Starting execution: UPLOAD
2016-03-01 05:20:17,151 [main] WARN  (RuntimeModelDataManager.java:318) - Reading RuntimeModelData: Runtime model data file does not exist.  Nothing to load: /var/local/ade/output/continuous/docker/runtimeModelData.ser
org.openmainframe.ade.exceptions.AdeInternalException: Database access error
at org.openmainframe.ade.dbUtils.ConnectionWrapper.failed(ConnectionWrapper.java:132)
at org.openmainframe.ade.impl.dataStore.DataStoreGroupsImpl.getUnassignedGroupInternalId(DataStoreGroupsImpl.java:145)
:
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Table 'GROUPS' was not locked with LOCK TABLES
at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:479)
:
```

In addition, a batch insert should only be flushed if there is data to be flushed.

### CODE REVIEW

**Comment by nealef** [comment]
CLA signed and submitted prior to PR being generated. Not sure why it's failing. I have my github ID associated with my LF login.

**Comment by jmertic** [comment]
@nealef Can you make sure the email address on your Github account matches the ones on your commit?

**Comment by nealef** [comment]
neale@sinenomine.net is now my primary (it was secondary)

@nealef <https://github.com/nealef>  Can you make sure the email address on
your Github account matches the ones on your commit?

**Comment by jmertic** [comment]
Did a fix on the CLA side, let me see if it will work now.

**Comment by jmertic** [comment]
Looks to be fixed now!

**Comment by nealef** [comment]
Thanks

**Comment by caffreyj** [comment]
Code reviewed
Merged into develop for regression test

**Pull request closed without merging**
